### PR TITLE
 Correction for https://github.com/xlab-si/xopera-examples/issues/33 and https://github.com/xlab-si/xopera-examples/issues/35

### PR DESCRIPTION
**Pull request by philippemerle**

### CODE REVIEW

**Review by anzoman — APPROVED** [review]
Looks okay, thanks @philippemerle!

**Review by anzoman — CHANGES_REQUESTED** [review]
@philippemerle as you probably see the merging is blocked, please rebase your branch onto current master and resolve the remaining git conflicts, so that we could proceed with merging.

**Review by anzoman — APPROVED** [review]

**Comment by anzoman** [comment]
@philippemerle these are commit from your branch:

slika

And these are from this repo:

slika

You can see that after we merged your previous pull requests onto master the commits are different and were given different commit hashes and that's why we have so many commits in this PR intead of just the latest 6 commits that you created. So you could remove the commits that already exists and get them back by rebasing onto origin/master.

**Comment by philippemerle** [comment]
@anzoman More I am trying more this is worse:-( I would like to not waste my time as I still have other issues to report to you. So I think I should create a new fork, copy my modified files into it, remove the current PR, create a new PR, and  go back to school to learn git-rebase.

**Comment by anzoman** [comment]
@philippemerle sure, whatever suits you best, I think creating a fresh new fork and PR would be fine.

**Pull request closed without merging**
